_data/topnav.yml, index.md
#7 の修正となります。
topページとナビバー部分を修正しました。
@chihiro-adachi
=> Githubへのリンクを新リポジトリのURLに変更

_config.yml
=> Disqusでリアクション/コメントができるように機能追加。

_data/navigation.yml, _includes/head.html, _pages/contribution-guide/development.md, _pages/contribution-guide/overview.md
eccube3系ドキュメントにあるような本体開発環境の構築手順のセクションを追加しました。
=> 「本体開発に参加する」セクションを追加

_sass/minimal-mistakes/_navigation.scss, _sass/minimal-mistakes/_variables.scss, assets/css/main.scss
=> レイアウト調整　scss調整

_layouts/single.html
=> ページ内メニュー上部に、評価へのアンカーリンクを追加

_layouts/single.html
■修正箇所1
アンカーリンクの文言を変更
修正前：このページを評価する
修正後：ページを評価/質問する
■修正箇所2
コメント記載例を追加。
=> 評価/コメント記載を促すために文言を追記・変更

_pages/customize/customize_service.md
PurchaseFlowの説明になってるのでタイトルを変更。
Serviceのカスタマイズについてはそれはそれで記述が必要。
=> 内容がServiceのカスタマイズじゃない

_pages/api/startup-guide.md
=> タイトルが間違っていたので修正

_data/navigation.yml, _pages/design/css.md, index.md
#97 にて修正漏れとmd記法が間違っているところがあったので修正しました。
- メニューのタイトルの変更
- うまくリンクができていなかったところの修正
- スペースの統一
refs #92
=> CSSとSassの利用のmd記法の修正

_pages/quickstart/update.md
=> アップデート手順書に4.0.4を追加

_pages/customize/customize_service.md
ItemProcessorの説明の内容はコードだとItemValidatorになってる。ItemPreprocessorは使っているのかも不明
=> ItemProcessorなんか無い

_pages/quickstart/install.md
こちらのページのPVが多いのでGUIインストールの導線追加いたしました。
初心者向けインストールの下に記載しています。
=> GUIインストールのリンクを追加

_pages/plugin/spec.md
`[プラグインディレクトリ]/Resouce/services.yaml` -> `[プラグインディレクトリ]/Resouce/config/services.yaml`
=> services.yamlのパスを修正

_data/navigation.yml, _pages/customize/customize_order_state_machine.md, index.md
ページがなかったので追加しました。
refs https://github.com/EC-CUBE/ec-cube/pull/3325#issuecomment-657918944
=> 受注ステータスのカスタマイズのページを追加

_data/navigation.yml, _pages/plugin/naming.md, index.md
よく調べるのでドキュメントに写しました。
元の情報は以下。
https://github.com/EC-CUBE/sample-payment-plugin/issues/6
管理画面のルーティングは追記しています。
=> プラグインで推奨の命名規則を追加

_data/navigation.yml, _pages/design/messages.md
ECCUEB4.0.4でapp/Customize 以下にmessages.xx.yaml を置けるようになったためメッセージカスタマイズのページを追加しました。
=> メッセージカスタマイズのページを追加

_data/navigation.yml, index.md
- APIに関する記述が先祖返りしていたため削除
- 目次の１階層目にURLを設定するとメニューが閉じなくなるため修正
=> メニューのデザインを調整

_pages/quickstart/install.md
掲題のとおりです。
* コミュニティでも質問が出ていました。
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=24832&forum=2&post_id=100555
* 手順（実行コマンド）はマージされたPRのやり方に準拠しました。
https://github.com/EC-CUBE/ec-cube/pull/4746
* 項番をずらすと項番込みで引用されていた際などに困ったことになりそうなので *composer.pharファイルを生成* への加筆、としました。
=> インストール方法 composerバージョン1系に下げる手順を追加

_pages/quickstart/update_40_41.md
東京UGの勉強会で、 ServiceProvider を使用している方がいたようなので、サンプルコードを追加
=> app 廃止のサンプルコードを追加

_data/navigation.yml, index.md
=> プラグインカスタマイズをプラグイン開発に変更

_pages/plugin/spec.md
=> パッケージングのディレクトリを修正

_pages/quickstart/requirement.md
- 動作確認環境を[README.md](https://github.com/EC-CUBE/ec-cube#%E5%8B%95%E4%BD%9C%E7%A2%BA%E8%AA%8D%E7%92%B0%E5%A2%83) に合わせる
- PostgreSQL について、ユニットテスト、E2Eテストは 11 でクリアしているため検討が必要と思われる。(現在の最新は13.2)
=> 動作確認環境を README に合わせる

_pages/quickstart/requirement.md
- see https://github.com/EC-CUBE/ec-cube/issues/5007
=> システム要件に PostgreSQL のバージョン追加

_pages/quickstart/update.md
以下の脆弱性に関する対応
https://www.ec-cube.net/news/detail.php?news_id=383
=> 4.0.5以前の脆弱性の記述を追加してアップデート手順を4.0.5-p1に修正

_pages/quickstart/update_40_41.md
EC-CUBE 4.1 でのプラグインインストールテストの設定を追加しました。
=> EC-CUBE 4.1 でのプラグインインストールテストの設定を追加

_pages/co/co_faq.md
=> 20210909 co faq

_pages/quickstart/update41.md
- 既存の更新手順とは独立して作成
- 細かな文言や目次リンクは別途調整します
=> 4.0から4.1へのアップデート手順を追加

_pages/quickstart/requirement.md
4.1リリースに伴い、システム要件のDB部分のバージョンを更新しました
=> 4.1 システム要件 DB部分を更新

_pages/penetration-testing/index.md
see https://github.com/EC-CUBE/ec-cube/pull/5183#issuecomment-971121121
=> テスト自動化へのリンク追加

_data/navigation.yml, _pages/quickstart/latest_version.md, index.md
EC-CUBEの最新バージョンの関連情報をまとめたページを追加しました。
=> 最新バージョンのページを追加

_pages/customize/customize_formtype.md
「FormTypeのカスタマイズ」ページのTODOとなっていた部分をリンク化しました。
=> TODOコメントになっていた部分をリンク化

_pages/customize/customize_order_state_machine.md
「受注ステータスのカスタマイズ」ページのベタ書きになっていたURLをリンク化しました。
=> ベタ書きになっていたURLをリンク化

_pages/i18n/multilingualization.md
「多言語化」ページでベタ書きのURLになっていたのをリンク化しました。
=> ベタ書きのURLになっていたのをリンク化

_pages/i18n/session_settings.md
「セッション情報保存方法の変更 」ページでベタ書きURLをリンク化しました。
=> ベタ書きURLをリンク化

_pages/penetration-testing/quick_start.md
セキュリティテストのQuick Startページで外部サイトは別タブで開くようにしました。
=> 外部サイトは別タブで開くようにしました

_pages/penetration-testing/about_owaspzap/index.md
「OWASP ZAP について」ページの外部サイトのリンクは別タブで開くようにしました。
=> 外部サイトのリンクは別タブで開くようにしました

_pages/penetration-testing/review/index.md
「テスト評価」ページの外部ページは別タブで開くように修正しました。
=> 外部ページは別タブで開くように修正

_pages/penetration-testing/improvement/index.md
「セキュリティの改善 」ページで外部サイトは別タブで開くように修正しました。
=> 外部サイトは別タブで開くように修正

_pages/quickstart/requirement.md
- Windows7, IE11 ではテストしていないと思われるため変更
- iOS, Android のバージョンも見直した方がよいかも(レスポンシブなので不要？)
=> IEは非推奨になったため、動作確認ブラウザを Edge に変更

_pages/customize/customize_repository.md
refs https://github.com/EC-CUBE/ec-cube/pull/4978
=> リポジトリのカスタマイズにログイン履歴検索のカスタマイズを追加

_pages/co/co.md
=> phpのバージョンを更新

_pages/quickstart/composer_web_installer.md
issues #5365 インストール　ドキュメントの間違い)の 「ComposerからWebインストーラでインストールする」部分対応
=> (fix)issues #5365

_pages/quickstart/docker_compose_install.md, _pages/quickstart/docker_install.md
Docker Desktop for Windows を利用している場合はワークスペースをWSL上に作成することでパフォーマンスの劣化を避けられる旨を既存のドキュメントに追加
[Docker Desktop WSL 2 バックエンド | ベストプラクティス](https://docs.docker.jp/docker-for-windows/wsl.html#wsl-bestpractices)
以下ページの冒頭に記述を追加。
- Docker Compose を使用してインストールする
- Docker を使用してインストールする
---
- [Docker Desktop WSL 2 バックエンド ](https://docs.docker.jp/docker-for-windows/wsl.html) 
#271 で開発環境構築手順自体の見直しを提案してみているのですが、とりあえず既存のドキュメント部分に一文追記。
=> docker-composeインストール方法にWindows環境向けパフォーマンス対策追記

_pages/co/co_faq.md
受注データ一括削除プラグイン for EC-CUBE4.2 への案内を追加しました
※内容は @yKazihara さんと事前調整済み
https://doc4.ec-cube.net/co/co_faq
=> 受注データ一括削除プラグイン for EC-CUBE4.2 への案内を追加

_pages/quickstart/update_42_43.md
以下のPRを取り込むにあたって、マイグレーションガイドを追記しました。
https://github.com/EC-CUBE/ec-cube/pull/5147
=> feat:purchaseflow.yamlの改修内容
