pages/quickstart/install.md

Eccube４系は、インターネット インフォメーション サービス (IIS) はサポートしていないため、こちらの記述は不要と判断し削除しています。

サポート外のため、IISでの設定例を削除

---

_includes/head/custom.html

「./assets」で指定するとダメでした。
ページのルートからassetsを探しに行くので表示されます。
https://doc4.ec-cube.net/documents/request

サブディレクトリのページでFaviconが表示されない不具合を修正。

---

_pages/quickstart/install.md

以下、DockerComposeを用いたインストールに対応するドキュメントを追加しました
https://github.com/EC-CUBE/ec-cube/pull/4391
https://github.com/EC-CUBE/ec-cube/pull/4397
私見ではありますが、Dockerの知見があればDBなども揃えて開発環境を整えるのは一番早いかなと思いますので、下記一文を加えていますが、ぜひご意見をいただきたいです。
```
開発環境として関連サービス(DB、メールデバッグ環境等)も含め手軽に一括構築したい場合におすすめの方法です
```
また、基本的に本番環境ではなく開発環境を想定しています。

本体インストール方法「Docker Composeを使用してインストールする」を追加

---

_includes/head.html
_layouts/single.html

GitHub上で直接ページを編集してPRを作成できるリンクを追加しました。
http://jekyll.github.io/github-metadata/edit-on-github-link/

ページを編集するリンク追加

---

_data/navigation.yml
_pages/api/startup-guide.md
index.md

Web APIのベータ版の簡単な利用ガイドを追加
新規項目として追加しています。
内容はこちらで確認いただけます。
https://github.com/okazy/doc4.ec-cube.net/blob/experimental/api/_pages/api/startup-guide.md

Web APIのベータ版の簡単な利用ガイドを追加

---

_pages/quickstart/install.md

`bin/console` コマンドは `root` ユーザで実行しないのが無難。

Docker Compose環境利用時に、DBにSQLiteを利用すると書込権限がなくエラーとなる問題に対処.

---

_data/navigation.yml
_pages/customize/customize_service.md
index.md

[左メニューの項目名と、実際のページのタイトルが、食い違っている #84](https://github.com/EC-CUBE/doc4.ec-cube.net/issues/84#issue-604457036)
こちらの修正しました。

タイトルが違っていたところを変更しました。

---

_data/navigation.yml
index.md

公式サイトの開発協力ページへのリンクを追加しました。
プラグインなどの開発にも同様の手順で参加できるので、「本体」の文言は消しました。

公式サイトの開発協力ページへのリンクを追加

---

_data/navigation.yml

サイドナビのSameSite_Cookieへのリンクが切れていたので修正しました。

SameSite_Cookieへのリンクが切れていたので修正しました。

---

_data/navigation.yml

できればファイル配置が _pages/i18n/ となっているのもやめたかったが影響が大きそうだったので取り急ぎサイドナビだけ修正しました。

navigation.yml のカテゴリの名称を「多言語化」から、より汎用的な「設定変更」に修正

---

_pages/quickstart/hotfix_samesite_cookie.md

close #96
要点は以下
- 4.0.4でSameSite Cookieの新仕様に対応したのでアップデートをお願いします。
- Hot-fixパッチの変更内容は4.0.4へのアップデートのファイル削除&差し替え対象のため切り戻しは不要。
- ただしアップデート時にファイルの削除は確実に行っていただく必要がある旨を記載。
- 想定では切り戻し手順は不要だが、変更内容がわからなくなってはいけないと思ったので残している。

SameSite Cookieのドキュメントを更新

---

_pages/development-tools/mail-catcher.md
_pages/i18n/currency.md
_pages/i18n/debug_mode.md
_pages/i18n/environmental_setting.md
_pages/i18n/multilingualization.md
_pages/i18n/timezone.md
_pages/quickstart/cli.md
_pages/quickstart/gui_mac_install.md
_pages/quickstart/gui_win_install.md
_pages/quickstart/install.md
_pages/quickstart/permission.md
_pages/quickstart/web-installer.md

タイポ修正 (forder -> folder)
Jekyll のドキュメントに folder or forder パラメータについての記載は見当たらなかったが、 folder が正しいだろうということでfolderに統一しました。

タイポ修正 (forder -> folder)

---

_data/navigation.yml
_pages/design/css.md
_pages/design/sass.md
index.md

CSSとSassのページを分けました。
ディレクトリ階層の表現を見やすいようにしました。
Sassのページでは、4.0.3と４.0.4のビルド方法の違いを記載
4.0.4パッケージ版でのWindowsのビルド不具合についても記載

CSSとSassのページを分け、SassのページにはEC-CUBE4.0.4の内容も記載

---

_pages/customize/customize_entity.md

Proxy を生成した後、それをデータベースへ反映する際はキャッシュクリアが必要のようです。
（キャッシュクリアを行わないとDoctrineがEntiryの拡張を認識しませんでした）
その旨をドキュメントに明記すると良いと思います。
ご検討よろしくお願いします！（私は1日ハマりました…）

Entity拡張をデータベースへ反映する際はキャッシュ削除が必要な旨を明記

---

_pages/quickstart/install.md

EC-CUBEはデフォルトでprodでインストールされるようになった。
`bin/console server:run` はdevでないと使えないので、 `--env=dev` を付与しました。
refs https://github.com/EC-CUBE/ec-cube/pull/4699

`bin/console server:run` はdevでないと使えないので `--env=dev` を付与

---

_pages/customize/customize_order_state_machine.md

ステートマシン説明ページのサンプルコードですが、useのパスが間違っていたので動きませんでした。
修正したコードを送ります。

サンプルコードのuseのパスが間違っていたのを修正

---

_pages/customize/customize_service.md

PurchaseFlow の Processor の説明を最新化しました。
また、説明を実行される順番に並び替えました。

PurchaseFlow の Processor の説明を最新化

---

_data/navigation.yml
_pages/sample-code/add-youtube-to-product-detail.md

Youtube動画を商品情報に追加するサンプルを追加

---

_pages/customize/customize_service.md

ValidatableItemProcessorはEC-CUBE本体に用意されていないのでItemValidatorに変更。

継承クラスをItemValidatorに変更

---

_pages/customize/customize_entity.md

Applicationは4.1で削除されるしApplicationのインジェクションの記述もないため、
$app['orm.em']を$this->entityMangerに変更しました。

$app['orm.em']を$this->entityMangerに変更

---

_data/navigation.yml
_pages/quickstart/dotenv.md
_pages/quickstart/install.md
index.md

.env ファイルの利用についての項目が埋もれていたので別ページを作成

---

_pages/quickstart/update.md

アップデート手順のプロキシ削除の手順を修正
プロキシファイルは `app/proxy/entity/` 直下に生成されなくなった

アップデート手順のプロキシ削除の手順を修正

---

_pages/penetration-testing/quick_start.md
_pages/penetration-testing/testing/context.md
_pages/penetration-testing/testing/settings.md
_pages/quickstart/install.md
_pages/quickstart/install_docker-compose_405orlower.md

- https://github.com/EC-CUBE/ec-cube/pull/4955
- EC-CUBE4.0.5以下の場合は記事を分割しました

docker-compose ファイルを分割に伴う修正

---

_data/navigation.yml
index.md

フィードバックフォームアンケートの撤去により、ドキュメントにあるフォードバックフォームへのリンクを削除しました。

フィードバックフォームリンクの削除

---

_pages/co/co_naming_rules.md

coの内部的な管理に利用しているものなのでユーザーが意識するものではない。
PHPのnamespaceと混乱するので削除。

namespaceは内部的に管理しているものなのでドキュメントには不要

---

_pages/quickstart/install.md

- docker-compose の環境変数を使用した場合に、 `eccube:install` コマンドの対話モードで設定した値が無効化されてしまうため、以下のような不具合が発生する
- authmagic が相違するため、ログインできない
- 意図した DATABASE_URL や MAILER_URL を使用できない
- 非対話モードを使用するよう明記

docker-compose を使用する場合は、必ず非対話モードを使用する旨を追記

---

_pages/quickstart/update_40_41.md

4.1マイグレーションガイドのオーナーズストア経由でのプラグインインストールテストを修正しました。
package-api の URL が間違っていました。
また EC-CUBE 4.1-beta3 のリリースに伴い、文言を修正しました。

4.1マイグレーションガイドのオーナーズストア経由でのプラグインインストールテストを修正しました。

---

_pages/co/co_git.md

app > Customize
app > template
html > template
の配下はファイルやディレクトリを新規作成してGit管理されるため、サブディレクトリの表記を削除。
またディレクトリもGit管理対象であることを説明に追加。

Git管理対象となるディレクトリの表現を修正

---

_pages/co/co_customize_dir_usage.md

お問い合わせでよく尋ねられる公開鍵設定手順とGoogleグループアカウント使用の際の手順を追加しました。

coカスタマイズディレクトリ利用方法に公開鍵設定の記述を追加

---

_data/navigation.yml

「初学者向け情報」が「はじめに」の上にあるのが違和感あるので、移動させました。

左メニューの「初学者向け情報」の順番を入れ替え

---

_data/navigation.yml
_pages/quickstart/update.md
_pages/quickstart/update41.md
_pages/quickstart/update_40_41.md

- 4.1へのバージョンアップページをメニューで上の方に表示するように変更。
- タイトルをわかりやすいように変更。

バージョンアップのメニューとタイトル整頓

---

_pages/co/co_faq.md

coのFAQページに、よく問い合わせのあるコアコードを触らずに上書きする方法のリンクを記載しました。

coのFAQページにコアコードの上書き方法の説明を追加

---

_pages/co/co_customize_dir_usage.md

coのブランチが4.0用固定となっていたのを、4.1用のブランチも併記するようにしました。

ec-cube.co カスタマイズディレクトリ利用方法ページの4.1対応

---

_pages/customize/customize_controller.md

「Controllerのカスタマイズ」ページでURLがベタ書きになっていた部分をリンク化しました。

べた書きになっていたURLをリンクへ修正

---

_pages/i18n/currency.md

「通貨」ページでURLがベタ書きになっていたのをリンク化しました。

ベタ書きURLをリンク化

---

_pages/penetration-testing/index.md

「EC-CUBE Penetration Testing with OWASP ZAP」ページでDoc4以外のサイトリンクは別タブで開くようにしました。

Doc4以外のサイトリンクは別タブで開くようにしました

---

_pages/plugin/spec.md

Macでプラグインをアーカイブしたときに `._PluginManager.php` のような `._` で始まるファイルがアーカイブに含まれることがある。
これらのファイルが含まれると環境によってはエラーが発生してしまうので、環境変数 `COPYFILE_DISABLE` を指定して `._` ファイルが含まれないようにする。

Macでプラグインアーカイブ時に `._` で始まるファイルを含めないようにする

---

_config.yml

config.yml にて `theme` と `remote_theme` の両方を指定していると、GitHub Actions でのビルド時に以下のエラーとなるため、config から theme を削除しました
```
github-pages 222 | Error:  The minimal-mistakes-jekyll theme could not be found.
```

ビルドエラー解消のため、config.yml から theme を削除

---

_pages/quickstart/requirement.md

[252](https://github.com/EC-CUBE/doc4.ec-cube.net/pull/252)で話題に上がった、OSバージョンの表記が不要というコメントを受けて削除しました。

動作確認ブラウザからOSバージョン表記削除

---

_pages/security-guideline/coding.md

前回のMasterマージ時にhtmlが正しく出力されない原因を調査、対処したものがこちらになります。
jekyllのマクロとtwigのマクロが同じ構文だったため、ご認識されていました。
エスケープ処理を追加したので問題なく表示されるのを確認しております。

jekyllとのマクロ衝突を回避（エスケープ処理を追加）

---

_pages/co/co_faq.md

Facebook連携プラグインは提供を停止しているので、現状に合わせた案内に修正しました。

Instagramショッピング機能についてのFAQを現状に合わせて修正

---

_pages/quickstart/requirement.md

EC-CUBE4.2系の必須PHPライブラリ：sodium 拡張の追加

EC-CUBE4.2.0のソフトウェア要件（必須PHPライブラリ）などのドキュメントの修正

---

_pages/co/co_security.md

個人情報取り扱いについてpdfへのリンク修正
/co/co_security
※大まかな流れの変更はありません。
■修正前
個人情報の取扱いについて を参照してください。
リンク先：https://www.ec-cube.co/pdf/privacy_policy.pdf
■修正後
個人情報保護方針、並びに個人情報の取扱いについて を参照してください
リンク先(個人情報保護方針)：https://www.ec-cube.net/policy/privacy.php
リンク先(個人情報の取扱いについて)：https://www.ec-cube.net/policy/

個人情報取り扱いについてpdfへのリンク修正

---

Gemfile

以下の問題対処の根治対応
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/302
Dockerコンテナ立ち上げ時に落ちてしまう原因がwebrickが見つからないことに起因するため、
Gemfileに設定を追加

jekyllのDockerコンテナ立ち上げ失敗に対処

---

_data/navigation.yml
_pages/plugin/error.md
index.md

プラグイン導入時以外のトラブル対処方法も記載されているので、タイトルを汎用的なものに変更しました。
※内容は @yKazihara さんと事前調整済み
- https://doc4.ec-cube.net/plugin_error 
- https://doc4.ec-cube.net/ ：目次の中
- 左サイドバー
↓
詳細はコメントご確認ください

プラグイン導入時以外のトラブル対処方法も記載されているので、タイトルを汎用的なものに変更

---

_pages/quickstart/latest_version.md
_pages/quickstart/requirement.md

EC-CUBE 4.3のリリースに伴い、ドキュメントの最新バージョン情報を修正しました。
- [最新バージョン](https://doc4.ec-cube.net/quickstart/latest_version)において、リストが4.2となっていたため、4.3に修正
- [システム要件](https://doc4.ec-cube.net/quickstart/requirement)に4.3を追加
- [最新バージョン](https://doc4.ec-cube.net/quickstart/latest_version)の修正画面
- [システム要件](https://doc4.ec-cube.net/quickstart/requirement)の修正画面

EC-CUBE 4.3リリースによる最新バージョン修正
